DROP TABLE BOOKS;
CREATE TABLE IF NOT EXISTS BOOKS(
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255),
    AUTHOR VARCHAR(60),
    PRICE INT
);

INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ('Envar sin egen professor', 'Falstaff, Fakir', 150);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ('Castafiores juveler', 'Herg?', 70);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ('Tintin i Tibet', 'Herg?', 70);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ('Emma', 'Jane Austen', 80);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ('Madame Bovary', 'Gustave Flaubert', 90);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ('Om en vinternatt en resande', 'Italo Calvino', 50);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("School", "Catherine G. Burke", 784);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("School", "Julie Murray", 593);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("School bullying", "Peter Smith", 14);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("School", "Stephanie Reid", 139);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("School Matters", "Peter Mortimore", 728);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Art School", "Steven Henry Madoff", 863);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("The Nature of School Bullying", "P. K. Smith", 184);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("School", "Ellen Rudin", 297);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("500 tips for school improvement", "Helen Horne", 438);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Design School Confidential", "Steven Heller", 644);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Coding", "Riley Barnes", 574);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Coding Theory", "San Ling", 431);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Introduction to Coding Theory", "Ron Roth", 998);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Audio Coding", "Yuli You", 43);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Coding", "Knute Axelson", 665);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Modern Coding Theory", "Tom Richardson", 809);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Network Coding Fundamentals", "Christina Fragouli", 446);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Error Correction Coding", "Todd K. Moon", 596);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Coding Theory", "J. H. van Lint", 660);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Claire Llewellyn", 513);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Ian F. Mahaney", 959);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Mari C. Schuh", 889);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Darlene R. Stille", 297);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Julie Murray", 721);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Chris Woodford", 774);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Adele Richardson", 129);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Chris Oxlade", 67);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "John Farndon", 580);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Electricity", "Harriet McGregor", 163);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Wood", "Fine Woodworking", 969);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Wood", "Dietrich Fengel", 831);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Wood", "Joachim Radkau", 444);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Wood", "Harvey Green", 154);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Wood", "Sara L. Kras", 383);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Wood", "John F. Siau", 570);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("The Retreat from Class", "Ellen Meiksins Wood", 891);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Understanding Wood", "R. Bruce Hoadley", 954);
INSERT INTO BOOKS(TITLE, AUTHOR, PRICE) VALUES ("Wood", "American Society for Testing & Materials", 815);
